unitree_sdk2_go2:

  # used in LeggedHWLoop.cpp
  loop_frequency: 500
  cycle_time_error_threshold: 0.002
  thread_priority: 95

  network_interface: lo  # 'lo' for simulation, 'eth0' for real robot
  joint_names:
    # order of joints aligns with that in unitree sdk2
    - FR_hip_joint
    - FR_thigh_joint
    - FR_calf_joint
    - FL_hip_joint
    - FL_thigh_joint
    - FL_calf_joint
    - RR_hip_joint
    - RR_thigh_joint
    - RR_calf_joint
    - RL_hip_joint
    - RL_thigh_joint
    - RL_calf_joint
  imu:
    handle_name: base_imu   # name of ImuSensorHandle in ros control
    frame_id: imu_link      # name of imu's frame_id in urdf
    topic_name: imu_data