controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 300

  rl_controller:
    type: legged/RLController
    frequency: 150

  static_controller:
    type: legged/StaticController
    frequency: 100