# This configuration file is used for mujoco simulation without unitree_sdk2
legged_mujoco:
  # used in legged_mujoco/src/main.cc
  robot: go2
  robot_scene: scene.xml
  description_pkg: unitree_go2_description

  # used in LeggedMujocoHWLoop.cpp
  loop_frequency: 500
  cycle_time_error_threshold: 0.002
  thread_priority: 95

  # used in LeggedMujocoHW.cpp
  imu:
    handle_name: base_imu   # name of ImuSensorHandle in ros control
    frame_id: imu_link      # name of imu's frame_id in urdf
    orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
    angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
    linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
    topic_name: imu_data
  base_link: pelvis   # it should align with the name in mujoco model

  use_unitree_sdk2: True